= Opalia Service SQL

This project is an OSGi component that manages an embedded instance of
https://github.com/h2database/h2database[H2 Database] or manages connectors for some other SQL databases. It provides
an API for a type-safe access to the database via plain SQL.

Download new versions from the Git repository https://github.com/OpaliaSystems/opalia-service-sql.

=== Getting Started

The component is handled by the Service Component Runtime (SCR) and becomes automatically available when all
dependencies are resolved. Once the component becomes available, a transactional instance can be created from the
database service. All SQL statements should be placed in such a transaction.

[source,scala]
----
val transactional = databaseService.newTransactional()

    transactional.withTransaction {
      implicit executor =>

        Query(
          """
            |CREATE TABLE Person (
            |  id INT NOT NULL,
            |  name VARCHAR(120) NOT NULL,
            |  counter INT NOT NULL,
            |  extra VARCHAR(120) NULL,
            |  PRIMARY KEY (id),
            |);
          """.stripMargin)
          .execute[IgnoredResult]()
    }
----

==== Configuration

The configuration is done by https://github.com/lightbend/config[HOCON]. Examples are available in directory
./testing/src/test/resources/ to get a quick insight into supported operations.

==== Executing a query

If the SQL query needs dynamic parameters, these can be added by declaring placeholders like {this} inside the
query clause. Each parameter is assigned to a value with the 'on' function. The execution returns with a 'Result'
object, which needs to be transformed. This object provides some meta data about the execution of the query.

[source,scala]
----
  Query(
    """
      |SELECT P1.name AS name, P1.counter AS counter
      |FROM Person P1
      |WHERE P1.counter > ? AND P1.extra = ?;
    """.stripMargin)
    .on("1", 42)
    .on("2", "foo")
    .execute[IndexedSeqResult]()
    .transform(row => (row[String]("name"), row[Int]("counter")))
----

The result of a query is designed as a table with rows and columns. Choose a concrete 'Result' type to get the
correct quantity of rows.

[source,scala]
----
// #M = 0
myQuery
.execute[IgnoredResult]()

// #M = 1
val x: String =
  myQuery
    .execute[SingleResult]()
    .transform(row => row[String]("name"))

// #M = 0..1
val x: Option[String] =
  myQuery
    .execute[SingleOptResult]()
    .transform(row => row[String]("name"))

// #M = 0..N
val x: IndexedSeq[String] =
  myQuery
    .execute[IndexedSeqResult]()
    .transform(row => row[String]("name"))

// #M = 1..N
val x: IndexedSeq[String] =
  myQuery
    .execute[IndexedNonEmptySeqResult]()
    .transform(row => row[String]("name"))
----

The API comes with many mappers to handle native Java types and some common types. Additional mappers for custom types
can be easily added.

=== License

Copyright (c) 2019 Eric Löffler

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

_http://www.apache.org/licenses/LICENSE-2.0_

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
